# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 382)
        MainWindow.setMinimumSize(QtCore.QSize(655, 213))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 671, 371))
        self.groupBox.setMinimumSize(QtCore.QSize(641, 181))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.errorMessageLabel = QtWidgets.QLabel(self.groupBox)
        self.errorMessageLabel.setGeometry(QtCore.QRect(20, 500, 621, 181))
        self.errorMessageLabel.setText("")
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 671, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 631, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 581, 251))
        self.pushButton.setMinimumSize(QtCore.QSize(151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.wmPageEdit = QtWidgets.QLineEdit(self.tab_2)
        self.wmPageEdit.setEnabled(False)
        self.wmPageEdit.setGeometry(QtCore.QRect(270, 20, 350, 31))
        self.wmPageEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wmPageEdit.setFont(font)
        self.wmPageEdit.setAutoFillBackground(True)
        self.wmPageEdit.setReadOnly(False)
        self.wmPageEdit.setObjectName("wmPageEdit")
        self.secretKeyLAbel = QtWidgets.QLabel(self.tab_2)
        self.secretKeyLAbel.setGeometry(QtCore.QRect(20, 160, 241, 41))
        self.secretKeyLAbel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.secretKeyLAbel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secretKeyLAbel.setFont(font)
        self.secretKeyLAbel.setObjectName("secretKeyLAbel")
        self.secretKeyEdit = QtWidgets.QLineEdit(self.tab_2)
        self.secretKeyEdit.setEnabled(False)
        self.secretKeyEdit.setGeometry(QtCore.QRect(270, 170, 350, 31))
        self.secretKeyEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.secretKeyEdit.setFont(font)
        self.secretKeyEdit.setAutoFillBackground(True)
        self.secretKeyEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.secretKeyEdit.setReadOnly(False)
        self.secretKeyEdit.setObjectName("secretKeyEdit")
        self.pageUrlLabel = QtWidgets.QLabel(self.tab_2)
        self.pageUrlLabel.setGeometry(QtCore.QRect(20, 10, 241, 41))
        self.pageUrlLabel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.pageUrlLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pageUrlLabel.setFont(font)
        self.pageUrlLabel.setObjectName("pageUrlLabel")
        self.consKeyEdit = QtWidgets.QLineEdit(self.tab_2)
        self.consKeyEdit.setEnabled(False)
        self.consKeyEdit.setGeometry(QtCore.QRect(270, 120, 350, 31))
        self.consKeyEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.consKeyEdit.setFont(font)
        self.consKeyEdit.setAutoFillBackground(True)
        self.consKeyEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.consKeyEdit.setReadOnly(False)
        self.consKeyEdit.setObjectName("consKeyEdit")
        self.consKeyLabel = QtWidgets.QLabel(self.tab_2)
        self.consKeyLabel.setGeometry(QtCore.QRect(20, 110, 241, 41))
        self.consKeyLabel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.consKeyLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consKeyLabel.setFont(font)
        self.consKeyLabel.setObjectName("consKeyLabel")
        self.wpApiUrlLabel = QtWidgets.QLabel(self.tab_2)
        self.wpApiUrlLabel.setGeometry(QtCore.QRect(20, 60, 241, 41))
        self.wpApiUrlLabel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wpApiUrlLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wpApiUrlLabel.setFont(font)
        self.wpApiUrlLabel.setObjectName("wpApiUrlLabel")
        self.wpApiUrlEdit = QtWidgets.QLineEdit(self.tab_2)
        self.wpApiUrlEdit.setEnabled(False)
        self.wpApiUrlEdit.setGeometry(QtCore.QRect(270, 70, 350, 31))
        self.wpApiUrlEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wpApiUrlEdit.setFont(font)
        self.wpApiUrlEdit.setAutoFillBackground(True)
        self.wpApiUrlEdit.setText("")
        self.wpApiUrlEdit.setReadOnly(False)
        self.wpApiUrlEdit.setObjectName("wpApiUrlEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Leafly WPAPI Sync"))
        self.groupBox.setTitle(_translate("MainWindow", "Leafly WPAPI Sync"))
        self.pushButton.setText(_translate("MainWindow", "Sync current products and pricing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sync"))
        self.secretKeyLAbel.setText(_translate("MainWindow", "WPAPI Secret Key:"))
        self.pageUrlLabel.setText(_translate("MainWindow", "Leafly page URL:"))
        self.consKeyLabel.setText(_translate("MainWindow", "WPAPI Consumer Key:"))
        self.wpApiUrlLabel.setText(_translate("MainWindow", "WPAPI URL:"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))

