# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 716)
        MainWindow.setMinimumSize(QtCore.QSize(655, 213))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 671, 701))
        self.groupBox.setMinimumSize(QtCore.QSize(641, 181))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(140, 390, 361, 71))
        self.pushButton.setMinimumSize(QtCore.QSize(151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.errorMessageLabel = QtWidgets.QLabel(self.groupBox)
        self.errorMessageLabel.setGeometry(QtCore.QRect(20, 500, 621, 181))
        self.errorMessageLabel.setText("")
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 651, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pageUrlLabel = QtWidgets.QLabel(self.groupBox_2)
        self.pageUrlLabel.setGeometry(QtCore.QRect(30, 40, 241, 41))
        self.pageUrlLabel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.pageUrlLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pageUrlLabel.setFont(font)
        self.pageUrlLabel.setObjectName("pageUrlLabel")
        self.consKeyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.consKeyLabel.setGeometry(QtCore.QRect(30, 140, 241, 41))
        self.consKeyLabel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.consKeyLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consKeyLabel.setFont(font)
        self.consKeyLabel.setObjectName("consKeyLabel")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 250, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.secretKeyEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.secretKeyEdit.setEnabled(False)
        self.secretKeyEdit.setGeometry(QtCore.QRect(280, 200, 350, 31))
        self.secretKeyEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.secretKeyEdit.setFont(font)
        self.secretKeyEdit.setAutoFillBackground(True)
        self.secretKeyEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.secretKeyEdit.setReadOnly(False)
        self.secretKeyEdit.setObjectName("secretKeyEdit")
        self.wmPageEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wmPageEdit.setEnabled(False)
        self.wmPageEdit.setGeometry(QtCore.QRect(280, 50, 350, 31))
        self.wmPageEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wmPageEdit.setFont(font)
        self.wmPageEdit.setAutoFillBackground(True)
        self.wmPageEdit.setReadOnly(False)
        self.wmPageEdit.setObjectName("wmPageEdit")
        self.consKeyEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.consKeyEdit.setEnabled(False)
        self.consKeyEdit.setGeometry(QtCore.QRect(280, 150, 350, 31))
        self.consKeyEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.consKeyEdit.setFont(font)
        self.consKeyEdit.setAutoFillBackground(True)
        self.consKeyEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.consKeyEdit.setReadOnly(False)
        self.consKeyEdit.setObjectName("consKeyEdit")
        self.secretKeyLAbel = QtWidgets.QLabel(self.groupBox_2)
        self.secretKeyLAbel.setGeometry(QtCore.QRect(30, 190, 241, 41))
        self.secretKeyLAbel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.secretKeyLAbel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secretKeyLAbel.setFont(font)
        self.secretKeyLAbel.setObjectName("secretKeyLAbel")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 250, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.wpApiUrlLabel = QtWidgets.QLabel(self.groupBox_2)
        self.wpApiUrlLabel.setGeometry(QtCore.QRect(30, 90, 241, 41))
        self.wpApiUrlLabel.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wpApiUrlLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wpApiUrlLabel.setFont(font)
        self.wpApiUrlLabel.setObjectName("wpApiUrlLabel")
        self.wpApiUrlEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wpApiUrlEdit.setEnabled(False)
        self.wpApiUrlEdit.setGeometry(QtCore.QRect(280, 100, 350, 31))
        self.wpApiUrlEdit.setMinimumSize(QtCore.QSize(350, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wpApiUrlEdit.setFont(font)
        self.wpApiUrlEdit.setAutoFillBackground(True)
        self.wpApiUrlEdit.setText("")
        self.wpApiUrlEdit.setReadOnly(False)
        self.wpApiUrlEdit.setObjectName("wpApiUrlEdit")
        #MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Leafly WPAPI Sync"))
        self.groupBox.setTitle(_translate("MainWindow", "Leafly WPAPI Sync"))
        self.pushButton.setText(_translate("MainWindow", "Sync current products and pricing"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings"))
        self.pageUrlLabel.setText(_translate("MainWindow", "Leafly page URL:"))
        self.consKeyLabel.setText(_translate("MainWindow", "WPAPI Consumer Key:"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.secretKeyLAbel.setText(_translate("MainWindow", "WPAPI Secret Key:"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.wpApiUrlLabel.setText(_translate("MainWindow", "WPAPI URL:"))

